<match rewrite.**>
  @type mongo
  host xxx.xxx.xxx.xxx
  port xxxxx
  database hoge
  collection '${tag}'
  remove_tag_prefix rewrite.
  <buffer>
    flush_mode interval
    retry_type exponential_backoff
    flush_thread_count 2
    flush_interval 5s
    retry_forever
    retry_max_interval 30
    chunk_limit_size 2M
    queue_limit_length 8
    overflow_action block
  </buffer>
</match>